[package]
name = "grm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecount = "0.6.3"
clap = { version = "3.2.17", features = ["clap_derive", "derive"] }
crossterm = "0.25.0"
